GRIDLINE = "gridline"
SHAPE = "shape"
SHAPE_TEXT = "shapetext"
EDGE = "edge"
LINK_LABEL = "linklabel"
WIRELESS_EDGE = "wireless"
ANTENNA = "antenna"
NODE_LABEL = "nodename"
NODE = "node"
WALLPAPER = "wallpaper"
SELECTION = "selectednodes"
MARKER = "marker"
ABOVE_WALLPAPER_TAGS = [
    GRIDLINE,
    SHAPE,
    SHAPE_TEXT,
    EDGE,
    LINK_LABEL,
    WIRELESS_EDGE,
    ANTENNA,
    NODE,
    NODE_LABEL,
]
ABOVE_SHAPE = [GRIDLINE, EDGE, LINK_LABEL, WIRELESS_EDGE, ANTENNA, NODE, NODE_LABEL]
COMPONENT_TAGS = [
    EDGE,
    NODE,
    NODE_LABEL,
    WALLPAPER,
    LINK_LABEL,
    ANTENNA,
    WIRELESS_EDGE,
    SELECTION,
    SHAPE,
    SHAPE_TEXT,
    MARKER,
]
