<%
  ifaces = ",".join(ifnames)
  arouted = ""
  if has_arouted:
    arouted = "tap %s_tap unicast %s push lo,%s resequence on" % (node.name, ip4_prefix, ifnames[0])
  if has_nhdp:
    flood = "ecds"
  elif has_olsr:
    flood = "smpr"
  else:
    flood = "cf"
%>
#!/bin/sh
# auto-generated by NrlSmf service
nrlsmf instance ${node.name}_smf ${ifaces} ${arouted} ${flood} hash MD5 log /var/log/nrlsmf.log < /dev/null > /dev/null 2>&1 &
