#!/bin/sh
# auto-generated by nrl.py:NrlSmf.generateconfig()
% if ifnames:
nrlsmf instance ${node.name}_smf \\
% if has_arouted:
  tap ${node.name}_tap unicast %s push lo,${ifnames[0]} resequence on \\
% endif
% if has_nhdp:
  ecds \\
% elif has_olsr:
  smpr \\
% else:
  cf \\
% endif
<%
  interfaces = ",".join(ifnames)
%>
  ${interfaces} hash MD5 log /var/log/nrlsmf.log < /dev/null > /dev/null 2>&1 &
% endif
