# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import core_pb2 as core__pb2


class CoreApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSession = channel.unary_unary(
        '/core.CoreApi/CreateSession',
        request_serializer=core__pb2.CreateSessionRequest.SerializeToString,
        response_deserializer=core__pb2.CreateSessionResponse.FromString,
        )
    self.DeleteSession = channel.unary_unary(
        '/core.CoreApi/DeleteSession',
        request_serializer=core__pb2.DeleteSessionRequest.SerializeToString,
        response_deserializer=core__pb2.DeleteSessionResponse.FromString,
        )
    self.GetSessions = channel.unary_unary(
        '/core.CoreApi/GetSessions',
        request_serializer=core__pb2.GetSessionsRequest.SerializeToString,
        response_deserializer=core__pb2.GetSessionsResponse.FromString,
        )
    self.GetSession = channel.unary_unary(
        '/core.CoreApi/GetSession',
        request_serializer=core__pb2.GetSessionRequest.SerializeToString,
        response_deserializer=core__pb2.GetSessionResponse.FromString,
        )
    self.GetSessionOptions = channel.unary_unary(
        '/core.CoreApi/GetSessionOptions',
        request_serializer=core__pb2.GetSessionOptionsRequest.SerializeToString,
        response_deserializer=core__pb2.GetSessionOptionsResponse.FromString,
        )
    self.SetSessionOptions = channel.unary_unary(
        '/core.CoreApi/SetSessionOptions',
        request_serializer=core__pb2.SetSessionOptionsRequest.SerializeToString,
        response_deserializer=core__pb2.SetSessionOptionsResponse.FromString,
        )
    self.GetSessionLocation = channel.unary_unary(
        '/core.CoreApi/GetSessionLocation',
        request_serializer=core__pb2.GetSessionLocationRequest.SerializeToString,
        response_deserializer=core__pb2.GetSessionLocationResponse.FromString,
        )
    self.SetSessionLocation = channel.unary_unary(
        '/core.CoreApi/SetSessionLocation',
        request_serializer=core__pb2.SetSessionLocationRequest.SerializeToString,
        response_deserializer=core__pb2.SetSessionLocationResponse.FromString,
        )
    self.SetSessionState = channel.unary_unary(
        '/core.CoreApi/SetSessionState',
        request_serializer=core__pb2.SetSessionStateRequest.SerializeToString,
        response_deserializer=core__pb2.SetSessionStateResponse.FromString,
        )
    self.NodeEvents = channel.unary_stream(
        '/core.CoreApi/NodeEvents',
        request_serializer=core__pb2.NodeEventsRequest.SerializeToString,
        response_deserializer=core__pb2.NodeEvent.FromString,
        )
    self.LinkEvents = channel.unary_stream(
        '/core.CoreApi/LinkEvents',
        request_serializer=core__pb2.LinkEventsRequest.SerializeToString,
        response_deserializer=core__pb2.LinkEvent.FromString,
        )
    self.SessionEvents = channel.unary_stream(
        '/core.CoreApi/SessionEvents',
        request_serializer=core__pb2.SessionEventsRequest.SerializeToString,
        response_deserializer=core__pb2.SessionEvent.FromString,
        )
    self.ConfigEvents = channel.unary_stream(
        '/core.CoreApi/ConfigEvents',
        request_serializer=core__pb2.ConfigEventsRequest.SerializeToString,
        response_deserializer=core__pb2.ConfigEvent.FromString,
        )
    self.ExceptionEvents = channel.unary_stream(
        '/core.CoreApi/ExceptionEvents',
        request_serializer=core__pb2.ExceptionEventsRequest.SerializeToString,
        response_deserializer=core__pb2.ExceptionEvent.FromString,
        )
    self.FileEvents = channel.unary_stream(
        '/core.CoreApi/FileEvents',
        request_serializer=core__pb2.FileEventsRequest.SerializeToString,
        response_deserializer=core__pb2.FileEvent.FromString,
        )
    self.AddNode = channel.unary_unary(
        '/core.CoreApi/AddNode',
        request_serializer=core__pb2.AddNodeRequest.SerializeToString,
        response_deserializer=core__pb2.AddNodeResponse.FromString,
        )
    self.GetNode = channel.unary_unary(
        '/core.CoreApi/GetNode',
        request_serializer=core__pb2.GetNodeRequest.SerializeToString,
        response_deserializer=core__pb2.GetNodeResponse.FromString,
        )
    self.EditNode = channel.unary_unary(
        '/core.CoreApi/EditNode',
        request_serializer=core__pb2.EditNodeRequest.SerializeToString,
        response_deserializer=core__pb2.EditNodeResponse.FromString,
        )
    self.DeleteNode = channel.unary_unary(
        '/core.CoreApi/DeleteNode',
        request_serializer=core__pb2.DeleteNodeRequest.SerializeToString,
        response_deserializer=core__pb2.DeleteNodeResponse.FromString,
        )
    self.GetNodeLinks = channel.unary_unary(
        '/core.CoreApi/GetNodeLinks',
        request_serializer=core__pb2.GetNodeLinksRequest.SerializeToString,
        response_deserializer=core__pb2.GetNodeLinksResponse.FromString,
        )
    self.AddLink = channel.unary_unary(
        '/core.CoreApi/AddLink',
        request_serializer=core__pb2.AddLinkRequest.SerializeToString,
        response_deserializer=core__pb2.AddLinkResponse.FromString,
        )
    self.EditLink = channel.unary_unary(
        '/core.CoreApi/EditLink',
        request_serializer=core__pb2.EditLinkRequest.SerializeToString,
        response_deserializer=core__pb2.EditLinkResponse.FromString,
        )
    self.DeleteLink = channel.unary_unary(
        '/core.CoreApi/DeleteLink',
        request_serializer=core__pb2.DeleteLinkRequest.SerializeToString,
        response_deserializer=core__pb2.DeleteLinkResponse.FromString,
        )
    self.GetHooks = channel.unary_unary(
        '/core.CoreApi/GetHooks',
        request_serializer=core__pb2.GetHooksRequest.SerializeToString,
        response_deserializer=core__pb2.GetHooksResponse.FromString,
        )
    self.AddHook = channel.unary_unary(
        '/core.CoreApi/AddHook',
        request_serializer=core__pb2.AddHookRequest.SerializeToString,
        response_deserializer=core__pb2.AddHookResponse.FromString,
        )
    self.GetMobilityConfigs = channel.unary_unary(
        '/core.CoreApi/GetMobilityConfigs',
        request_serializer=core__pb2.GetMobilityConfigsRequest.SerializeToString,
        response_deserializer=core__pb2.GetMobilityConfigsResponse.FromString,
        )
    self.GetMobilityConfig = channel.unary_unary(
        '/core.CoreApi/GetMobilityConfig',
        request_serializer=core__pb2.GetMobilityConfigRequest.SerializeToString,
        response_deserializer=core__pb2.GetMobilityConfigResponse.FromString,
        )
    self.SetMobilityConfig = channel.unary_unary(
        '/core.CoreApi/SetMobilityConfig',
        request_serializer=core__pb2.SetMobilityConfigRequest.SerializeToString,
        response_deserializer=core__pb2.SetMobilityConfigResponse.FromString,
        )
    self.MobilityAction = channel.unary_unary(
        '/core.CoreApi/MobilityAction',
        request_serializer=core__pb2.MobilityActionRequest.SerializeToString,
        response_deserializer=core__pb2.MobilityActionResponse.FromString,
        )
    self.GetServices = channel.unary_unary(
        '/core.CoreApi/GetServices',
        request_serializer=core__pb2.GetServicesRequest.SerializeToString,
        response_deserializer=core__pb2.GetServicesResponse.FromString,
        )
    self.GetServiceDefaults = channel.unary_unary(
        '/core.CoreApi/GetServiceDefaults',
        request_serializer=core__pb2.GetServiceDefaultsRequest.SerializeToString,
        response_deserializer=core__pb2.GetServiceDefaultsResponse.FromString,
        )
    self.SetServiceDefaults = channel.unary_unary(
        '/core.CoreApi/SetServiceDefaults',
        request_serializer=core__pb2.SetServiceDefaultsRequest.SerializeToString,
        response_deserializer=core__pb2.SetServiceDefaultsResponse.FromString,
        )
    self.GetNodeService = channel.unary_unary(
        '/core.CoreApi/GetNodeService',
        request_serializer=core__pb2.GetNodeServiceRequest.SerializeToString,
        response_deserializer=core__pb2.GetNodeServiceResponse.FromString,
        )
    self.GetNodeServiceFile = channel.unary_unary(
        '/core.CoreApi/GetNodeServiceFile',
        request_serializer=core__pb2.GetNodeServiceFileRequest.SerializeToString,
        response_deserializer=core__pb2.GetNodeServiceFileResponse.FromString,
        )
    self.SetNodeService = channel.unary_unary(
        '/core.CoreApi/SetNodeService',
        request_serializer=core__pb2.SetNodeServiceRequest.SerializeToString,
        response_deserializer=core__pb2.SetNodeServiceResponse.FromString,
        )
    self.SetNodeServiceFile = channel.unary_unary(
        '/core.CoreApi/SetNodeServiceFile',
        request_serializer=core__pb2.SetNodeServiceFileRequest.SerializeToString,
        response_deserializer=core__pb2.SetNodeServiceFileResponse.FromString,
        )
    self.ServiceAction = channel.unary_unary(
        '/core.CoreApi/ServiceAction',
        request_serializer=core__pb2.ServiceActionRequest.SerializeToString,
        response_deserializer=core__pb2.ServiceActionResponse.FromString,
        )
    self.GetWlanConfig = channel.unary_unary(
        '/core.CoreApi/GetWlanConfig',
        request_serializer=core__pb2.GetWlanConfigRequest.SerializeToString,
        response_deserializer=core__pb2.GetWlanConfigResponse.FromString,
        )
    self.SetWlanConfig = channel.unary_unary(
        '/core.CoreApi/SetWlanConfig',
        request_serializer=core__pb2.SetWlanConfigRequest.SerializeToString,
        response_deserializer=core__pb2.SetWlanConfigResponse.FromString,
        )
    self.GetEmaneConfig = channel.unary_unary(
        '/core.CoreApi/GetEmaneConfig',
        request_serializer=core__pb2.GetEmaneConfigRequest.SerializeToString,
        response_deserializer=core__pb2.GetEmaneConfigResponse.FromString,
        )
    self.SetEmaneConfig = channel.unary_unary(
        '/core.CoreApi/SetEmaneConfig',
        request_serializer=core__pb2.SetEmaneConfigRequest.SerializeToString,
        response_deserializer=core__pb2.SetEmaneConfigResponse.FromString,
        )
    self.GetEmaneModels = channel.unary_unary(
        '/core.CoreApi/GetEmaneModels',
        request_serializer=core__pb2.GetEmaneModelsRequest.SerializeToString,
        response_deserializer=core__pb2.GetEmaneModelsResponse.FromString,
        )
    self.GetEmaneModelConfig = channel.unary_unary(
        '/core.CoreApi/GetEmaneModelConfig',
        request_serializer=core__pb2.GetEmaneModelConfigRequest.SerializeToString,
        response_deserializer=core__pb2.GetEmaneModelConfigResponse.FromString,
        )
    self.SetEmaneModelConfig = channel.unary_unary(
        '/core.CoreApi/SetEmaneModelConfig',
        request_serializer=core__pb2.SetEmaneModelConfigRequest.SerializeToString,
        response_deserializer=core__pb2.SetEmaneModelConfigResponse.FromString,
        )
    self.GetEmaneModelConfigs = channel.unary_unary(
        '/core.CoreApi/GetEmaneModelConfigs',
        request_serializer=core__pb2.GetEmaneModelConfigsRequest.SerializeToString,
        response_deserializer=core__pb2.GetEmaneModelConfigsResponse.FromString,
        )
    self.SaveXml = channel.unary_unary(
        '/core.CoreApi/SaveXml',
        request_serializer=core__pb2.SaveXmlRequest.SerializeToString,
        response_deserializer=core__pb2.SaveXmlResponse.FromString,
        )
    self.OpenXml = channel.unary_unary(
        '/core.CoreApi/OpenXml',
        request_serializer=core__pb2.OpenXmlRequest.SerializeToString,
        response_deserializer=core__pb2.OpenXmlResponse.FromString,
        )


class CoreApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateSession(self, request, context):
    """session rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSessions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSessionOptions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetSessionOptions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSessionLocation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetSessionLocation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetSessionState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodeEvents(self, request, context):
    """event streams
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LinkEvents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SessionEvents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfigEvents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExceptionEvents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FileEvents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddNode(self, request, context):
    """node rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodeLinks(self, request, context):
    """link rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHooks(self, request, context):
    """hook rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddHook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMobilityConfigs(self, request, context):
    """mobility rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMobilityConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMobilityConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MobilityAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetServices(self, request, context):
    """service rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetServiceDefaults(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetServiceDefaults(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodeService(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodeServiceFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetNodeService(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetNodeServiceFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServiceAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWlanConfig(self, request, context):
    """wlan rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetWlanConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEmaneConfig(self, request, context):
    """emane rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetEmaneConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEmaneModels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEmaneModelConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetEmaneModelConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEmaneModelConfigs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveXml(self, request, context):
    """xml rpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenXml(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CoreApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSession': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSession,
          request_deserializer=core__pb2.CreateSessionRequest.FromString,
          response_serializer=core__pb2.CreateSessionResponse.SerializeToString,
      ),
      'DeleteSession': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSession,
          request_deserializer=core__pb2.DeleteSessionRequest.FromString,
          response_serializer=core__pb2.DeleteSessionResponse.SerializeToString,
      ),
      'GetSessions': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessions,
          request_deserializer=core__pb2.GetSessionsRequest.FromString,
          response_serializer=core__pb2.GetSessionsResponse.SerializeToString,
      ),
      'GetSession': grpc.unary_unary_rpc_method_handler(
          servicer.GetSession,
          request_deserializer=core__pb2.GetSessionRequest.FromString,
          response_serializer=core__pb2.GetSessionResponse.SerializeToString,
      ),
      'GetSessionOptions': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessionOptions,
          request_deserializer=core__pb2.GetSessionOptionsRequest.FromString,
          response_serializer=core__pb2.GetSessionOptionsResponse.SerializeToString,
      ),
      'SetSessionOptions': grpc.unary_unary_rpc_method_handler(
          servicer.SetSessionOptions,
          request_deserializer=core__pb2.SetSessionOptionsRequest.FromString,
          response_serializer=core__pb2.SetSessionOptionsResponse.SerializeToString,
      ),
      'GetSessionLocation': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessionLocation,
          request_deserializer=core__pb2.GetSessionLocationRequest.FromString,
          response_serializer=core__pb2.GetSessionLocationResponse.SerializeToString,
      ),
      'SetSessionLocation': grpc.unary_unary_rpc_method_handler(
          servicer.SetSessionLocation,
          request_deserializer=core__pb2.SetSessionLocationRequest.FromString,
          response_serializer=core__pb2.SetSessionLocationResponse.SerializeToString,
      ),
      'SetSessionState': grpc.unary_unary_rpc_method_handler(
          servicer.SetSessionState,
          request_deserializer=core__pb2.SetSessionStateRequest.FromString,
          response_serializer=core__pb2.SetSessionStateResponse.SerializeToString,
      ),
      'NodeEvents': grpc.unary_stream_rpc_method_handler(
          servicer.NodeEvents,
          request_deserializer=core__pb2.NodeEventsRequest.FromString,
          response_serializer=core__pb2.NodeEvent.SerializeToString,
      ),
      'LinkEvents': grpc.unary_stream_rpc_method_handler(
          servicer.LinkEvents,
          request_deserializer=core__pb2.LinkEventsRequest.FromString,
          response_serializer=core__pb2.LinkEvent.SerializeToString,
      ),
      'SessionEvents': grpc.unary_stream_rpc_method_handler(
          servicer.SessionEvents,
          request_deserializer=core__pb2.SessionEventsRequest.FromString,
          response_serializer=core__pb2.SessionEvent.SerializeToString,
      ),
      'ConfigEvents': grpc.unary_stream_rpc_method_handler(
          servicer.ConfigEvents,
          request_deserializer=core__pb2.ConfigEventsRequest.FromString,
          response_serializer=core__pb2.ConfigEvent.SerializeToString,
      ),
      'ExceptionEvents': grpc.unary_stream_rpc_method_handler(
          servicer.ExceptionEvents,
          request_deserializer=core__pb2.ExceptionEventsRequest.FromString,
          response_serializer=core__pb2.ExceptionEvent.SerializeToString,
      ),
      'FileEvents': grpc.unary_stream_rpc_method_handler(
          servicer.FileEvents,
          request_deserializer=core__pb2.FileEventsRequest.FromString,
          response_serializer=core__pb2.FileEvent.SerializeToString,
      ),
      'AddNode': grpc.unary_unary_rpc_method_handler(
          servicer.AddNode,
          request_deserializer=core__pb2.AddNodeRequest.FromString,
          response_serializer=core__pb2.AddNodeResponse.SerializeToString,
      ),
      'GetNode': grpc.unary_unary_rpc_method_handler(
          servicer.GetNode,
          request_deserializer=core__pb2.GetNodeRequest.FromString,
          response_serializer=core__pb2.GetNodeResponse.SerializeToString,
      ),
      'EditNode': grpc.unary_unary_rpc_method_handler(
          servicer.EditNode,
          request_deserializer=core__pb2.EditNodeRequest.FromString,
          response_serializer=core__pb2.EditNodeResponse.SerializeToString,
      ),
      'DeleteNode': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteNode,
          request_deserializer=core__pb2.DeleteNodeRequest.FromString,
          response_serializer=core__pb2.DeleteNodeResponse.SerializeToString,
      ),
      'GetNodeLinks': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodeLinks,
          request_deserializer=core__pb2.GetNodeLinksRequest.FromString,
          response_serializer=core__pb2.GetNodeLinksResponse.SerializeToString,
      ),
      'AddLink': grpc.unary_unary_rpc_method_handler(
          servicer.AddLink,
          request_deserializer=core__pb2.AddLinkRequest.FromString,
          response_serializer=core__pb2.AddLinkResponse.SerializeToString,
      ),
      'EditLink': grpc.unary_unary_rpc_method_handler(
          servicer.EditLink,
          request_deserializer=core__pb2.EditLinkRequest.FromString,
          response_serializer=core__pb2.EditLinkResponse.SerializeToString,
      ),
      'DeleteLink': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteLink,
          request_deserializer=core__pb2.DeleteLinkRequest.FromString,
          response_serializer=core__pb2.DeleteLinkResponse.SerializeToString,
      ),
      'GetHooks': grpc.unary_unary_rpc_method_handler(
          servicer.GetHooks,
          request_deserializer=core__pb2.GetHooksRequest.FromString,
          response_serializer=core__pb2.GetHooksResponse.SerializeToString,
      ),
      'AddHook': grpc.unary_unary_rpc_method_handler(
          servicer.AddHook,
          request_deserializer=core__pb2.AddHookRequest.FromString,
          response_serializer=core__pb2.AddHookResponse.SerializeToString,
      ),
      'GetMobilityConfigs': grpc.unary_unary_rpc_method_handler(
          servicer.GetMobilityConfigs,
          request_deserializer=core__pb2.GetMobilityConfigsRequest.FromString,
          response_serializer=core__pb2.GetMobilityConfigsResponse.SerializeToString,
      ),
      'GetMobilityConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetMobilityConfig,
          request_deserializer=core__pb2.GetMobilityConfigRequest.FromString,
          response_serializer=core__pb2.GetMobilityConfigResponse.SerializeToString,
      ),
      'SetMobilityConfig': grpc.unary_unary_rpc_method_handler(
          servicer.SetMobilityConfig,
          request_deserializer=core__pb2.SetMobilityConfigRequest.FromString,
          response_serializer=core__pb2.SetMobilityConfigResponse.SerializeToString,
      ),
      'MobilityAction': grpc.unary_unary_rpc_method_handler(
          servicer.MobilityAction,
          request_deserializer=core__pb2.MobilityActionRequest.FromString,
          response_serializer=core__pb2.MobilityActionResponse.SerializeToString,
      ),
      'GetServices': grpc.unary_unary_rpc_method_handler(
          servicer.GetServices,
          request_deserializer=core__pb2.GetServicesRequest.FromString,
          response_serializer=core__pb2.GetServicesResponse.SerializeToString,
      ),
      'GetServiceDefaults': grpc.unary_unary_rpc_method_handler(
          servicer.GetServiceDefaults,
          request_deserializer=core__pb2.GetServiceDefaultsRequest.FromString,
          response_serializer=core__pb2.GetServiceDefaultsResponse.SerializeToString,
      ),
      'SetServiceDefaults': grpc.unary_unary_rpc_method_handler(
          servicer.SetServiceDefaults,
          request_deserializer=core__pb2.SetServiceDefaultsRequest.FromString,
          response_serializer=core__pb2.SetServiceDefaultsResponse.SerializeToString,
      ),
      'GetNodeService': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodeService,
          request_deserializer=core__pb2.GetNodeServiceRequest.FromString,
          response_serializer=core__pb2.GetNodeServiceResponse.SerializeToString,
      ),
      'GetNodeServiceFile': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodeServiceFile,
          request_deserializer=core__pb2.GetNodeServiceFileRequest.FromString,
          response_serializer=core__pb2.GetNodeServiceFileResponse.SerializeToString,
      ),
      'SetNodeService': grpc.unary_unary_rpc_method_handler(
          servicer.SetNodeService,
          request_deserializer=core__pb2.SetNodeServiceRequest.FromString,
          response_serializer=core__pb2.SetNodeServiceResponse.SerializeToString,
      ),
      'SetNodeServiceFile': grpc.unary_unary_rpc_method_handler(
          servicer.SetNodeServiceFile,
          request_deserializer=core__pb2.SetNodeServiceFileRequest.FromString,
          response_serializer=core__pb2.SetNodeServiceFileResponse.SerializeToString,
      ),
      'ServiceAction': grpc.unary_unary_rpc_method_handler(
          servicer.ServiceAction,
          request_deserializer=core__pb2.ServiceActionRequest.FromString,
          response_serializer=core__pb2.ServiceActionResponse.SerializeToString,
      ),
      'GetWlanConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetWlanConfig,
          request_deserializer=core__pb2.GetWlanConfigRequest.FromString,
          response_serializer=core__pb2.GetWlanConfigResponse.SerializeToString,
      ),
      'SetWlanConfig': grpc.unary_unary_rpc_method_handler(
          servicer.SetWlanConfig,
          request_deserializer=core__pb2.SetWlanConfigRequest.FromString,
          response_serializer=core__pb2.SetWlanConfigResponse.SerializeToString,
      ),
      'GetEmaneConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetEmaneConfig,
          request_deserializer=core__pb2.GetEmaneConfigRequest.FromString,
          response_serializer=core__pb2.GetEmaneConfigResponse.SerializeToString,
      ),
      'SetEmaneConfig': grpc.unary_unary_rpc_method_handler(
          servicer.SetEmaneConfig,
          request_deserializer=core__pb2.SetEmaneConfigRequest.FromString,
          response_serializer=core__pb2.SetEmaneConfigResponse.SerializeToString,
      ),
      'GetEmaneModels': grpc.unary_unary_rpc_method_handler(
          servicer.GetEmaneModels,
          request_deserializer=core__pb2.GetEmaneModelsRequest.FromString,
          response_serializer=core__pb2.GetEmaneModelsResponse.SerializeToString,
      ),
      'GetEmaneModelConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetEmaneModelConfig,
          request_deserializer=core__pb2.GetEmaneModelConfigRequest.FromString,
          response_serializer=core__pb2.GetEmaneModelConfigResponse.SerializeToString,
      ),
      'SetEmaneModelConfig': grpc.unary_unary_rpc_method_handler(
          servicer.SetEmaneModelConfig,
          request_deserializer=core__pb2.SetEmaneModelConfigRequest.FromString,
          response_serializer=core__pb2.SetEmaneModelConfigResponse.SerializeToString,
      ),
      'GetEmaneModelConfigs': grpc.unary_unary_rpc_method_handler(
          servicer.GetEmaneModelConfigs,
          request_deserializer=core__pb2.GetEmaneModelConfigsRequest.FromString,
          response_serializer=core__pb2.GetEmaneModelConfigsResponse.SerializeToString,
      ),
      'SaveXml': grpc.unary_unary_rpc_method_handler(
          servicer.SaveXml,
          request_deserializer=core__pb2.SaveXmlRequest.FromString,
          response_serializer=core__pb2.SaveXmlResponse.SerializeToString,
      ),
      'OpenXml': grpc.unary_unary_rpc_method_handler(
          servicer.OpenXml,
          request_deserializer=core__pb2.OpenXmlRequest.FromString,
          response_serializer=core__pb2.OpenXmlResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'core.CoreApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
