# syntax=docker/dockerfile:1
FROM ubuntu:20.04
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/.local/bin:${PATH}"
WORKDIR /opt

# install system dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    automake \
    pkg-config \
    libev-dev \
    nftables \
    iproute2 \
    ethtool \
    tk \
    bash \
    gem \
    rpm \
    ruby \
    ca-certificates \
    build-essential \
    git && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# install python and tools
ARG PYTHON_VERSION=3.10
ARG DOTENV_VERSION=2.8.1
ARG GRPC_VERSION=1.69.0
ARG INVOKE_VERSION=2.2.1
ARG POETRY_VERSION=1.8.5
RUN uv python install ${PYTHON_VERSION} && \
    uv tool install invoke==${INVOKE_VERSION} && \
    uv tool install poetry==${POETRY_VERSION} && \
    gem install dotenv -v ${DOTENV_VERSION} && \
    gem install fpm

# clone and build core
ARG BRANCH=master
RUN git clone https://github.com/coreemu/core.git && \
    cd core && \
    git checkout ${BRANCH} && \
    uv venv --python ${PYTHON_VERSION} venv && \
    uv pip install --python ./venv/bin/python grpcio==${GRPC_VERSION} grpcio-tools==${GRPC_VERSION} && \
    ./bootstrap.sh && \
    PYTHON=./venv/bin/python ./configure --prefix=/usr && \
    make -j$(nproc) && \
    make fpm
