# syntax=docker/dockerfile:1
FROM ubuntu:24.04
COPY --from=ghcr.io/astral-sh/uv:0.9.22 /uv /uvx /bin/
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/.local/bin:${PATH}"
WORKDIR /opt

# install python
ARG PYTHON_VERSION=3.13
RUN uv python install ${PYTHON_VERSION}

# install system dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    lsb-release \
    xterm \
    psmisc \
    tk \
    wget \
    iproute2 \
    iputils-ping \
    tcpdump && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# install frr
ARG FRRVER="frr-stable"
RUN curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null && \
    echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | tee -a /etc/apt/sources.list.d/frr.list && \
    apt-get update -y && \
    apt-get install -y frr frr-pythontools && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
ENV PATH="/usr/lib/frr:$PATH"

# install emane
ARG EMANE_VERSION=1.5.3
ARG EMANE_RELEASE=emane-${EMANE_VERSION}-release-1
ARG EMANE_PACKAGE=${EMANE_RELEASE}.ubuntu-24_04.amd64.tar.gz
RUN apt-get update -y && \
    wget -q https://adjacentlink.com/downloads/emane/${EMANE_PACKAGE} && \
    tar xf ${EMANE_PACKAGE} && \
    cd ${EMANE_RELEASE}/debs/ubuntu-24_04/amd64 && \
    rm emane-spectrum-tools*.deb emane-model-lte*.deb && \
    rm *dev*.deb && \
    apt-get install -y --no-install-recommends ./emane*.deb ./python3-emane_*.deb && \
    cd ../../../.. && \
    rm ${EMANE_PACKAGE} && \
    rm -rf ${EMANE_RELEASE} && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# install core
COPY --from=core-package /opt/core/core_*.deb .
RUN apt-get update -y && \
    PYTHON=$(uv python find ${PYTHON_VERSION}) apt-get install -y --no-install-recommends ./core_*.deb && \
    rm -f ${CORE_PACKAGE} && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# install emane python bindings with dependencies
ARG VENV_PATH=/opt/core/venv
COPY --from=emane-python /opt/emane-*.whl .
RUN uv pip install --python ${VENV_PATH} 'setuptools<81' ./emane-*.whl && \
    rm -f ./emane-*.whl

# set default directory
WORKDIR /root
