#!/bin/env bash
# enable xhost access to the root user, this will allow you to run the core-gui from the container
xhost +local:root

IMAGE_NAME="${1}"
if [[ -z "${IMAGE_NAME}" ]]; then
  echo "You must provide a CORE image name to run"
  exit 1
fi

sudo docker container rm -f core
sudo docker run -itd --name core -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    --privileged --init --pids-limit=0 "${IMAGE_NAME}" bash
