# syntax=docker/dockerfile:1
FROM centos:7
LABEL Description="CORE CentOS Image"

# define environment
ENV DEBIAN_FRONTEND=noninteractive

# install basic dependencies
RUN yum update -y && yum install -y python3 python3-pip python3-tkinter
RUN python3 -m pip install --upgrade pip

# install core
WORKDIR /opt/core
COPY core_*.rpm .
RUN yum install -y ./core_*.rpm
