name: Daemon Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.22"
      - name: install dependencies
        run: |
          cd daemon
          cp core/constants.py.in core/constants.py
          sed -i 's/required=True/required=False/g' core/emulator/coreemu.py
          uv sync
      - name: ruff
        run: |
          cd daemon
          uv run ruff check .
      - name: grpc
        run: |
          cd daemon/proto
          uv run python -m grpc_tools.protoc -I . --python_out=.. --grpc_python_out=.. core/api/grpc/*.proto
      - name: test
        run: |
          cd daemon
          uv run pytest --mock tests
